apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL
    type: postgres
    url: db:5432
    database: ai_powered_eco_db
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
    editable: true
